name: alebaffa/alessandrobaffacom
author:
  name: Alessandro Baffa
  email: alessandro.baffa@gmail.com
  url: 'https://www.alessandrobaffa.com'
copyright: 2015 Alessandro Baffa
description: Landing page of AlessandroBaffa.com website.
